### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by recepseyis** [ionutneagos/social-login-web-api#5]
Hello, I tried very hard, but I couldn't get past this error and log in, I wonder why
![token](https://github.com/ionutneagos/social-login-web-api/assets/15039145/5f27143b-3b3b-4693-9700-5337c6a4f7ff)
![token1](https://github.com/ionutneagos/social-login-web-api/assets/15039145/af795e94-6d88-48c5-bf0b-7996f83aece2)
![token2](https://github.com/ionutneagos/social-login-web-api/assets/15039145/d21c7d49-bcb4-4b57-a769-a227c4a1161f)
![token3](https://github.com/ionutneagos/social-login-web-api/assets/15039145/491684e3-71fe-450c-81d8-4a5555f54ec5)

**Comment by ionutneagos** [comment]
hi @recepseyis, 
I think the **clientid** in the angular app is not the same with **clientid** from API appsettings. Please check ClientId from both apps to have the same value. 

### API settings
```
  "Google": {
      "ClientId": "[Client Id from  Google OAuth Configuration]",
      "ClientSecret": [Client Secret from  Google OAuth Configuration]
    }
    
```
### Angular settings
```
 export const environment = {
  production: false,
  baseUrl: 'https://localhost:44329', //back-end address
  googleClientId: "googleClientId",  //Client Id from  Google OAuth Configuration [Client Id from  Google OAuth Configuration]
};
```
 Let me know if this works

**Comment by recepseyis** [comment]
I checked and both sides Google Client ID is the same

**Comment by ionutneagos** [comment]
Hi @recepseyis,

From what I can see, the error seems to be related to misconfiguration. Are you certain that the Client ID and oauthclient from Google OAuth client credentials are valid? I'd be happy to take a look at your code if you could share a snippet with me.

**Comment by recepseyis** [comment]
I just provided the login id and added it;


https://github.com/recepseyis/SocialLoginApiClient

**Comment by ionutneagos** [comment]
Hi @recepseyis,

I just noticed that the first time you tried, you used the client ID from the Angular app. This resulted in an invalid 'aud' claim because the 'ClientSecret' in the API's 'appsettings.json' file under 'Google' is not set. To resolve this, you need to configure a project on https://console.cloud.google.com/.

For guidance, you can refer to the following link: https://developers.google.com/workspace/guides/create-credentials

Take into consideration that the client ID from this repository is configured by me, but I didn't expose the client secret.
